[package]
name = "infinitier_pvrz_resource"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Reader and writer for the PVRZ compressed texture format used in Infinity Engine Enhanced Editions"
readme = "readme.md"
keywords = ["pvrz", "pvr", "texture", "infinity-engine", "baldurs-gate"]

[dependencies]
flate2 = { workspace = true }
image = { workspace = true }
infinitier_datasource = { workspace = true }
log = { workspace = true }
texpresso = { workspace = true }
texture2ddecoder = { workspace = true }

[dev-dependencies]
infinitier_test_utils = { workspace = true }
tempfile = { workspace = true }
