[package]
name = "infinitier_bam_importer"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
description = ""
readme = "readme.md"
keywords = []

[dependencies]
image = { workspace = true }
infinitier_datasource = { workspace = true }
infinitier_fs = { workspace = true }
infinitier_pvr_importer = { workspace = true }

[dev-dependencies]
infinitier_test_utils = { workspace = true }
