[package]
name = "mve_player"
edition.workspace = true
version.workspace = true

[[bin]]
name = "mve_player"
path = "src/main.rs"

[dependencies]
eframe = "0.33"
infinitier_datasource = { workspace = true }
infinitier_mve_decoder = { workspace = true }
rodio = { version = "0.20", default-features = false, features = ["symphonia-mp3"] }
