[package]
name = "infinitier_explorer_gpui"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
infinitier_core = { workspace = true }
gpui = { workspace = true }
image = { workspace = true }

clap = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
