[package]
name = "infinitier_datasource"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
description = ""
readme = "readme.md"
keywords = []

[dependencies]
encoding_rs = { workspace = true }
flate2 = { workspace = true }