[package]
name = "infinitier_key_importer"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Reader for the KEY resource index format used in Infinity Engine games"
readme = "readme.md"
keywords = ["key", "chitin", "index", "infinity-engine", "baldurs-gate"]

[dependencies]
infinitier_common = { workspace = true }
infinitier_datasource = { workspace = true }
log = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
infinitier_fs = { workspace = true }
infinitier_test_utils = { workspace = true }
