use infinitier_acm_decoder::{AcmDecoder, AcmInfo, OutputChannels};
use infinitier_datasource::DataSource;
use infinitier_test_utils::{get_assets_path, get_target_path};
use sha2::{Digest, Sha256};
use std::{fs, path::PathBuf};

/// Integration tests: decode every bundled ACM fixture and check the
/// SHA-256 hash of the produced WAV matches the reference output
/// generated by the original C libacm tool (acmtool).
fn decode_and_hash(acm_rel: &str) -> (String, AcmInfo) {
    let acm_path = get_assets_path().join("resources/ACM").join(acm_rel);

    let wav_rel = PathBuf::from(acm_rel).with_extension("wav");
    let wav_path = get_target_path().join("acm_test_output").join(&wav_rel);
    fs::create_dir_all(wav_path.parent().unwrap()).unwrap();

    let data = DataSource::new(acm_path.clone());
    let reader = data.reader().unwrap();

    let mut dec = AcmDecoder::open(reader, OutputChannels::Original)
        .unwrap_or_else(|e| panic!("cannot decode {}: {e}", acm_path.display()));

    println!(
        "{}: {} Hz, {} ch, {} samples",
        acm_rel,
        dec.info.rate,
        dec.info.channels,
        dec.info.total_values / dec.info.channels,
    );

    let info = dec.info.clone();

    dec.decode_to_file(&wav_path)
        .unwrap_or_else(|e| panic!("decode error in {}: {e}", acm_path.display()));

    let wav_bytes = fs::read(&wav_path).unwrap();
    let hash = Sha256::digest(&wav_bytes)
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect();

    (hash, info)
}

// ── 2ch / 22050 Hz / A:7/16  (BG1) ──────────────────────────────────────────

/// `bg/Bf1j4.ACM` — Length: 0:00 Chans:2(2) Freq:22050 A:7/16 kbps:146
#[test]
fn test_bg_bf1j4() {
    let (got, _info) = decode_and_hash("bg/Bf1j4.ACM");
    assert_eq!(
        got, "18d02d5777bda38e06dc357a027a39cd39755f770b55c54517f1bbce5f7e44bf",
        "WAV hash mismatch for bg/Bf1j4.ACM",
    );
}

/// `bg/Bf1d1.ACM` — Length: 0:02 Chans:2(2) Freq:22050 A:7/16 kbps:143
#[test]
fn test_bg_bf1d1() {
    let (got, _info) = decode_and_hash("bg/Bf1d1.ACM");
    assert_eq!(
        got, "13169bea5f12cb591e56ad7f50bfb858f43c4ed154b7206d814e37194d367b1f",
        "WAV hash mismatch for bg/Bf1d1.ACM",
    );
}

/// `bg/Bc2g2.ACM` — Length: 0:03 Chans:2(2) Freq:22050 A:7/16 kbps:142
#[test]
fn test_bg_bc2g2() {
    let (got, _info) = decode_and_hash("bg/Bc2g2.ACM");
    assert_eq!(
        got, "715c74831bb76264e13e3022b73c763c84d92e8228c4e25868dc67d32bb138c8",
        "WAV hash mismatch for bg/Bc2g2.ACM",
    );
}

/// `bg/BL2endE.ACM` — Length: 0:04 Chans:2(2) Freq:22050 A:7/16 kbps:132
#[test]
fn test_bg_bl2ende() {
    let (got, _info) = decode_and_hash("bg/BL2endE.ACM");
    assert_eq!(
        got, "ed46f469f2d5e40a47f4f7751137591b246418f181366ad84d376be570a31403",
        "WAV hash mismatch for bg/BL2endE.ACM",
    );
}

// ── 2ch / 44100 Hz / A:7/16  (BG2 EE — unique sample rate) ──────────────────

/// `bg2_ee/oh6200a.acm` — Length: 1:04 Chans:2(2) Freq:44100 A:7/16 kbps:607
#[test]
fn test_bg2_ee_oh6200a() {
    let (got, info) = decode_and_hash("bg2_ee/oh6200a.acm");
    assert_eq!(
        got, "c4593f4ddbd4c48ef2380879c7c0571d33d78fbe178f1d18bc15f59e2a769e95",
        "WAV hash mismatch for bg2ee/oh6200a.acm",
    );
    assert_eq!(info.acm_channels, 2);
    assert_eq!(info.rate, 44100);
    assert_eq!(info.samples(), 2846878);
}

// ── 2ch / 22050 Hz / A:8/16 ──────────────────────────────────────────────────

/// `bg2/BC1A1.acm` — Length: 0:01 Chans:2(2) Freq:22050 A:8/16 kbps:143
#[test]
fn test_bg2_bc1a1() {
    let (got, _info) = decode_and_hash("bg2/BC1A1.acm");
    assert_eq!(
        got, "2dfbdc5e3608eb5148e1e1bb01de5a361c7438dfd1045fdb9ea4bf1a95fcde3c",
        "WAV hash mismatch for bg2/BC1A1.acm",
    );
}

/// `iwd/B6F3.acm` — Length: 0:01 Chans:2(2) Freq:22050 A:8/16 kbps:147
#[test]
fn test_iwd_b6f3() {
    let (got, _info) = decode_and_hash("iwd/B6F3.acm");
    assert_eq!(
        got, "fde55667e3a2ca696d65de22cdf9efa51b3db130cbcd6a06e98e86d53ce18dc4",
        "WAV hash mismatch for iwd/B6F3.acm",
    );
}

/// `iwd2/B5b4.acm` — Length: 0:01 Chans:2(2) Freq:22050 A:8/16 kbps:186
#[test]
fn test_iwd2_b5b4() {
    let (got, info) = decode_and_hash("iwd2/B5b4.acm");
    assert_eq!(
        got, "bb5ed490d6d78107e5f370b17df99c3ac9d02dccab69d4d94e0f3efdb4d39124",
        "WAV hash mismatch for iwd2/B5b4.acm",
    );
    assert_eq!(info.acm_channels, 2);
    assert_eq!(info.rate, 22050);
    assert_eq!(info.samples(), 35009);
}

/// `iwd_ee/b6f3.acm` — Length: 0:01 Chans:2(2) Freq:22050 A:8/16 kbps:147
#[test]
fn test_iwd_ee_b6f3() {
    let (got, _info) = decode_and_hash("iwd_ee/b6f3.acm");
    assert_eq!(
        got, "fde55667e3a2ca696d65de22cdf9efa51b3db130cbcd6a06e98e86d53ce18dc4",
        "WAV hash mismatch for iwd_ee/b6f3.acm",
    );
}

// ── 1ch / 22050 Hz / A:8/16 ──────────────────────────────────────────────────

/// `iwd/B1d2.acm` — Length: 0:06 Chans:1(1) Freq:22050 A:8/16 kbps:90
#[test]
fn test_iwd_b1d2() {
    let (got, _info) = decode_and_hash("iwd/B1d2.acm");
    assert_eq!(
        got, "2ac935a033b6749727f77006a3f14f2312c068c3b7071e4b8a99d1bced80abd1",
        "WAV hash mismatch for iwd/B1d2.acm",
    );
}

/// `iwd/B4a2.acm` — Length: 0:10 Chans:1(1) Freq:22050 A:8/16 kbps:89
#[test]
fn test_iwd_b4a2() {
    let (got, info) = decode_and_hash("iwd/B4a2.acm");
    assert_eq!(
        got, "aa381c6170f5d8168934eaa014802e845ef815ec853731ee3e14de091ae3b75a",
        "WAV hash mismatch for iwd/B4a2.acm",
    );
    assert_eq!(info.acm_channels, 1);
    assert_eq!(info.rate, 22050);
    assert_eq!(info.samples(), 229452);
}

/// `pst/bt5c3.acm` — Length: 0:02 Chans:1(1) Freq:22050 A:8/16 kbps:72
#[test]
fn test_pst_bt5c3() {
    let (got, _info) = decode_and_hash("pst/bt5c3.acm");
    assert_eq!(
        got, "363eb4a5a191f0981be1f8e18cb1f7c35f30682dc059a148cb35e737c0e1f975",
        "WAV hash mismatch for pst/bt5c3.acm",
    );
}

/// `pst/bt2zc1.acm` — Length: 0:07 Chans:1(1) Freq:22050 A:8/16 kbps:71
#[test]
fn test_pst_bt2zc1() {
    let (got, _info) = decode_and_hash("pst/bt2zc1.acm");
    assert_eq!(
        got, "4ef8d7f11990a9392e163cb8b8ffb85c270b26c78881e6910a99a1431ce10056",
        "WAV hash mismatch for pst/bt2zc1.acm",
    );
}
