use infinitier_acm_decoder::{AcmDecoder, AcmInfo, OutputChannels};
use infinitier_datasource::DataSource;
use infinitier_test_utils::{get_assets_path, get_target_path};
use sha2::{Digest, Sha256};
use std::{fs, path::PathBuf};

/// Integration tests: decode every bundled ACM fixture and check the
/// SHA-256 hash of the produced WAV matches the reference output
/// generated by the original C libacm tool (acmtool).
fn decode_and_hash(acm_rel: &str) -> (String, AcmInfo) {
    let acm_path = get_assets_path().join("resources/ACM").join(acm_rel);

    let wav_rel = PathBuf::from(acm_rel).with_extension("wav");
    let wav_path = get_target_path().join("acm_test_output").join(&wav_rel);
    fs::create_dir_all(wav_path.parent().unwrap()).unwrap();

    let data = DataSource::new(acm_path.clone());

    let mut dec = AcmDecoder::open(&data, OutputChannels::Original, acm_rel)
        .unwrap_or_else(|e| panic!("cannot decode {}: {e}", acm_path.display()));

    println!(
        "{}: {} Hz, {} ch, {} samples",
        acm_rel,
        dec.info.rate,
        dec.info.channels,
        dec.info.total_values / dec.info.channels,
    );

    let info = dec.info.clone();

    dec.decode_to_file(&wav_path)
        .unwrap_or_else(|e| panic!("decode error in {}: {e}", acm_path.display()));

    let wav_bytes = fs::read(&wav_path).unwrap();
    let hash = Sha256::digest(&wav_bytes)
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect();

    (hash, info)
}

// ── 2ch / 22050 Hz / A:7/16  (BG1) ──────────────────────────────────────────

/// `bg/Bf1j4.ACM` — Length: 0:00 Chans:2(2) Freq:22050 A:7/16 kbps:146
#[test]
fn test_bg_bf1j4() {
    let (got, _info) = decode_and_hash("bg/Bf1j4.ACM");
    assert_eq!(
        got, "18d02d5777bda38e06dc357a027a39cd39755f770b55c54517f1bbce5f7e44bf",
        "WAV hash mismatch for bg/Bf1j4.ACM",
    );
}

/// `bg/Bf1d1.ACM` — Length: 0:02 Chans:2(2) Freq:22050 A:7/16 kbps:143
#[test]
fn test_bg_bf1d1() {
    let (got, _info) = decode_and_hash("bg/Bf1d1.ACM");
    assert_eq!(
        got, "13169bea5f12cb591e56ad7f50bfb858f43c4ed154b7206d814e37194d367b1f",
        "WAV hash mismatch for bg/Bf1d1.ACM",
    );
}

/// `bg/Bc2g2.ACM` — Length: 0:03 Chans:2(2) Freq:22050 A:7/16 kbps:142
#[test]
fn test_bg_bc2g2() {
    let (got, _info) = decode_and_hash("bg/Bc2g2.ACM");
    assert_eq!(
        got, "715c74831bb76264e13e3022b73c763c84d92e8228c4e25868dc67d32bb138c8",
        "WAV hash mismatch for bg/Bc2g2.ACM",
    );
}

/// `bg/BL2endE.ACM` — Length: 0:04 Chans:2(2) Freq:22050 A:7/16 kbps:132
#[test]
fn test_bg_bl2ende() {
    let (got, _info) = decode_and_hash("bg/BL2endE.ACM");
    assert_eq!(
        got, "ed46f469f2d5e40a47f4f7751137591b246418f181366ad84d376be570a31403",
        "WAV hash mismatch for bg/BL2endE.ACM",
    );
}

// ── 2ch / 44100 Hz / A:7/16  (BG2 EE — unique sample rate) ──────────────────

/// `bg2_ee/oh6200a.acm` — Length: 1:04 Chans:2(2) Freq:44100 A:7/16 kbps:607
#[test]
fn test_bg2_ee_oh6200a() {
    let (got, info) = decode_and_hash("bg2_ee/oh6200a.acm");
    assert_eq!(
        got, "c4593f4ddbd4c48ef2380879c7c0571d33d78fbe178f1d18bc15f59e2a769e95",
        "WAV hash mismatch for bg2ee/oh6200a.acm",
    );
    assert_eq!(info.acm_channels, 2);
    assert_eq!(info.rate, 44100);
    assert_eq!(info.samples(), 2846878);
}

// ── 2ch / 22050 Hz / A:8/16 ──────────────────────────────────────────────────

/// `bg2/BC1A1.acm` — Length: 0:01 Chans:2(2) Freq:22050 A:8/16 kbps:143
#[test]
fn test_bg2_bc1a1() {
    let (got, _info) = decode_and_hash("bg2/BC1A1.acm");
    assert_eq!(
        got, "2dfbdc5e3608eb5148e1e1bb01de5a361c7438dfd1045fdb9ea4bf1a95fcde3c",
        "WAV hash mismatch for bg2/BC1A1.acm",
    );
}

/// `iwd/B6F3.acm` — Length: 0:01 Chans:2(2) Freq:22050 A:8/16 kbps:147
#[test]
fn test_iwd_b6f3() {
    let (got, _info) = decode_and_hash("iwd/B6F3.acm");
    assert_eq!(
        got, "fde55667e3a2ca696d65de22cdf9efa51b3db130cbcd6a06e98e86d53ce18dc4",
        "WAV hash mismatch for iwd/B6F3.acm",
    );
}

/// `iwd2/B5b4.acm` — Length: 0:01 Chans:2(2) Freq:22050 A:8/16 kbps:186
#[test]
fn test_iwd2_b5b4() {
    let (got, info) = decode_and_hash("iwd2/B5b4.acm");
    assert_eq!(
        got, "bb5ed490d6d78107e5f370b17df99c3ac9d02dccab69d4d94e0f3efdb4d39124",
        "WAV hash mismatch for iwd2/B5b4.acm",
    );
    assert_eq!(info.acm_channels, 2);
    assert_eq!(info.rate, 22050);
    assert_eq!(info.samples(), 35009);
}

/// `iwd_ee/b6f3.acm` — Length: 0:01 Chans:2(2) Freq:22050 A:8/16 kbps:147
#[test]
fn test_iwd_ee_b6f3() {
    let (got, _info) = decode_and_hash("iwd_ee/b6f3.acm");
    assert_eq!(
        got, "fde55667e3a2ca696d65de22cdf9efa51b3db130cbcd6a06e98e86d53ce18dc4",
        "WAV hash mismatch for iwd_ee/b6f3.acm",
    );
}

// ── 1ch / 22050 Hz / A:8/16 ──────────────────────────────────────────────────

/// `iwd/B1d2.acm` — Length: 0:06 Chans:1(1) Freq:22050 A:8/16 kbps:90
#[test]
fn test_iwd_b1d2() {
    let (got, _info) = decode_and_hash("iwd/B1d2.acm");
    assert_eq!(
        got, "2ac935a033b6749727f77006a3f14f2312c068c3b7071e4b8a99d1bced80abd1",
        "WAV hash mismatch for iwd/B1d2.acm",
    );
}

/// `iwd/B4a2.acm` — Length: 0:10 Chans:1(1) Freq:22050 A:8/16 kbps:89
#[test]
fn test_iwd_b4a2() {
    let (got, info) = decode_and_hash("iwd/B4a2.acm");
    assert_eq!(
        got, "aa381c6170f5d8168934eaa014802e845ef815ec853731ee3e14de091ae3b75a",
        "WAV hash mismatch for iwd/B4a2.acm",
    );
    assert_eq!(info.acm_channels, 1);
    assert_eq!(info.rate, 22050);
    assert_eq!(info.samples(), 229452);
}

/// `pst/bt5c3.acm` — Length: 0:02 Chans:1(1) Freq:22050 A:8/16 kbps:72
#[test]
fn test_pst_bt5c3() {
    let (got, _info) = decode_and_hash("pst/bt5c3.acm");
    assert_eq!(
        got, "363eb4a5a191f0981be1f8e18cb1f7c35f30682dc059a148cb35e737c0e1f975",
        "WAV hash mismatch for pst/bt5c3.acm",
    );
}

/// `pst/bt2zc1.acm` — Length: 0:07 Chans:1(1) Freq:22050 A:8/16 kbps:71
#[test]
fn test_pst_bt2zc1() {
    let (got, _info) = decode_and_hash("pst/bt2zc1.acm");
    assert_eq!(
        got, "4ef8d7f11990a9392e163cb8b8ffb85c270b26c78881e6910a99a1431ce10056",
        "WAV hash mismatch for pst/bt2zc1.acm",
    );
}

/// Test that can decode WAVC files
#[test]
fn test_decode_wavc() {
    let wavc_path = get_assets_path().join("resources/WAV/1GROMG09.WAVC");
    let data = DataSource::new(wavc_path);
    let mut dec = AcmDecoder::open(&data, OutputChannels::Original, "1GROMG09.WAVC").unwrap();
    let temp = tempfile::NamedTempFile::new().unwrap();
    dec.decode_to_file(temp.path()).unwrap();

    let created_wav_hash = Sha256::digest(fs::read(temp.path()).unwrap());
    let wav_hash =
        Sha256::digest(fs::read(get_assets_path().join("resources/WAV/1GROMG09.WAV")).unwrap());

    assert_eq!(created_wav_hash, wav_hash);
}

// ── reset() ─────────────────────────────────────────────────────────────────

/// Decodes the named fixture from scratch and returns the full PCM buffer.
fn fresh_decode_all(acm_rel: &str) -> Vec<i16> {
    let acm_path = get_assets_path().join("resources/ACM").join(acm_rel);
    let data = DataSource::new(acm_path);
    let mut dec = AcmDecoder::open(&data, OutputChannels::Original, acm_rel).unwrap();
    dec.decode_all().unwrap()
}

/// `reset()` after a complete decode produces bit-identical samples on the
/// second run — the canonical "play it again" use case.
#[test]
fn test_reset_after_full_decode_matches_fresh_decode() {
    let acm_path = get_assets_path().join("resources/ACM").join("bg/Bf1d1.ACM");
    let data = DataSource::new(acm_path);

    let mut dec = AcmDecoder::open(&data, OutputChannels::Original, "bg/Bf1d1.ACM").unwrap();
    let info_before = dec.info.clone();
    let first = dec.decode_all().unwrap();
    assert_eq!(dec.samples_decoded(), info_before.total_values);

    dec.reset().unwrap();
    // Header must come back identical and the position counter must be zeroed.
    assert_eq!(dec.info.channels, info_before.channels);
    assert_eq!(dec.info.rate, info_before.rate);
    assert_eq!(dec.info.total_values, info_before.total_values);
    assert_eq!(dec.samples_decoded(), 0);

    let second = dec.decode_all().unwrap();
    assert_eq!(
        first.len(),
        second.len(),
        "sample count mismatch after reset"
    );
    assert!(
        first == second,
        "samples differ after reset: first run produced different bytes than second"
    );
}

/// `reset()` mid-stream — partway through a decode — must wipe leftover
/// block/wrapbuf state. If `wrapbuf` (juggle's stateful edge buffer) leaked
/// across the reset, the first samples after the reset would diverge from a
/// cold-start decode.
#[test]
fn test_reset_midstream_recovers_clean_state() {
    let acm_rel = "bg2/BC1A1.acm";
    let acm_path = get_assets_path().join("resources/ACM").join(acm_rel);
    let data = DataSource::new(acm_path);

    let mut dec = AcmDecoder::open(&data, OutputChannels::Original, acm_rel).unwrap();
    // Drain the first ~1000 frames to force several blocks + a partial one.
    let mut throwaway = vec![0i16; 1000 * dec.info.channels as usize];
    let drained = dec.read_samples(&mut throwaway).unwrap();
    assert!(drained > 0, "expected some samples before reset");

    dec.reset().unwrap();
    let after_reset = dec.decode_all().unwrap();

    let fresh = fresh_decode_all(acm_rel);
    assert_eq!(
        after_reset, fresh,
        "reset+decode_all must match fresh decode"
    );
}

/// Resetting twice in a row is a no-op vs resetting once — guarantees the
/// reset path is itself idempotent (matters for callers that call it
/// defensively, e.g. on track-load).
#[test]
fn test_reset_is_idempotent() {
    let acm_rel = "iwd/B1d2.acm";
    let acm_path = get_assets_path().join("resources/ACM").join(acm_rel);
    let data = DataSource::new(acm_path);

    let mut dec = AcmDecoder::open(&data, OutputChannels::Original, acm_rel).unwrap();
    let _ = dec.decode_all().unwrap();

    dec.reset().unwrap();
    dec.reset().unwrap();
    let twice = dec.decode_all().unwrap();

    let fresh = fresh_decode_all(acm_rel);
    assert_eq!(twice, fresh, "double reset must match fresh decode");
}

/// Reset interacts correctly with [`AcmDecoder::decode_to_file`] — after a
/// reset, writing the WAV produces the same SHA-256 as the first write.
#[test]
fn test_reset_then_decode_to_file_matches_first_write() {
    use sha2::{Digest, Sha256};
    use std::fs;

    let acm_rel = "iwd/B6F3.acm";
    let acm_path = get_assets_path().join("resources/ACM").join(acm_rel);
    let data = DataSource::new(acm_path);

    let out_dir = get_target_path().join("acm_test_output").join("reset");
    fs::create_dir_all(&out_dir).unwrap();
    let first_path = out_dir.join("first.wav");
    let second_path = out_dir.join("second.wav");

    let mut dec = AcmDecoder::open(&data, OutputChannels::Original, acm_rel).unwrap();
    dec.decode_to_file(&first_path).unwrap();
    dec.reset().unwrap();
    dec.decode_to_file(&second_path).unwrap();

    let h1 = Sha256::digest(fs::read(&first_path).unwrap());
    let h2 = Sha256::digest(fs::read(&second_path).unwrap());
    assert_eq!(
        h1, h2,
        "WAV hash differs between the original write and the post-reset write"
    );
}

/// A reset preserves the [`OutputChannels`] override picked at `open` time.
#[test]
fn test_reset_preserves_output_channels_override() {
    // bg/Bf1j4.ACM is natively stereo; force mono and confirm the override
    // survives a reset.
    let acm_path = get_assets_path().join("resources/ACM").join("bg/Bf1j4.ACM");
    let data = DataSource::new(acm_path);

    let mut dec = AcmDecoder::open(&data, OutputChannels::Mono, "bg/Bf1j4.ACM").unwrap();
    assert_eq!(dec.info.channels, 1);
    assert_eq!(dec.info.acm_channels, 2, "header says native stereo");

    let _ = dec.decode_all().unwrap();
    dec.reset().unwrap();
    assert_eq!(
        dec.info.channels, 1,
        "OutputChannels::Mono must survive reset"
    );
    assert_eq!(dec.info.acm_channels, 2);
}
