#!/usr/bin/env python3
"""
Generate per-frame SHA-256 fixtures for the IWD2 cutscene corpus.

For each of the 7 .mve files, runs FFmpeg to dump the entire video as raw
YUV420p (piped, never written to disk), hashes each frame independently,
and emits a single text fixture file consumed by the Rust corpus test.

Format (one fixture per line, sectioned by file):

    [<relative path>] width height frame_count
    <sha256 hex of frame 0>
    <sha256 hex of frame 1>
    ...

Re-running is idempotent — the fixture file is overwritten in full.

Usage:
    python3 gen_iwd2_fixtures.py [iwd2_root]

Default iwd2_root: /home/ufo/Temp/Games/Icewind Dale 2
"""

from __future__ import annotations

import argparse
import hashlib
import os
import struct
import subprocess
import sys
from pathlib import Path

# (relative path, frame width, frame height) — the dimensions are fixed per
# file and known from `ffprobe`; baked in here so we don't have to parse the
# Bink header ourselves.
FILES = [
    ("Data/BISlogo.mve", 640, 320),
    ("Data/Credits.mve", 640, 320),
    ("Data/Nvidia.mve", 640, 480),
    ("Data/WOTC.mve", 640, 320),
    ("CD2/Data/END.mve", 640, 480),
    ("CD2/Data/Intro.mve", 640, 480),
    ("CD2/Data/Middle.mve", 640, 480),
]


def hash_frames(src: Path, w: int, h: int) -> list[str]:
    """Pipe FFmpeg's YUV output through; hash each `frame_size` chunk."""
    frame_size = w * h + 2 * (w // 2) * (h // 2)  # YUV420p
    proc = subprocess.Popen(
        [
            "ffmpeg",
            "-loglevel", "error",
            "-i", str(src),
            "-f", "rawvideo",
            "-pix_fmt", "yuv420p",
            "-",
        ],
        stdout=subprocess.PIPE,
    )
    assert proc.stdout is not None
    hashes: list[str] = []
    buf = b""
    while True:
        chunk = proc.stdout.read(frame_size - len(buf))
        if not chunk:
            break
        buf += chunk
        while len(buf) >= frame_size:
            frame, buf = buf[:frame_size], buf[frame_size:]
            hashes.append(hashlib.sha256(frame).hexdigest())
    proc.wait()
    if proc.returncode != 0:
        raise RuntimeError(f"ffmpeg exited {proc.returncode} on {src}")
    if buf:
        raise RuntimeError(
            f"ffmpeg returned {len(buf)} trailing bytes that don't form a full frame for {src}"
        )
    return hashes


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "iwd2_root",
        nargs="?",
        default="/home/ufo/Temp/Games/Icewind Dale 2",
        type=Path,
    )
    args = parser.parse_args()

    here = Path(__file__).resolve().parent
    out_path = here / "iwd2_frames.txt"

    lines: list[str] = []
    lines.append("# IWD2 cutscene per-frame SHA-256 fixtures")
    lines.append("# Generated by gen_iwd2_fixtures.py via FFmpeg")
    lines.append("# Pixel format: yuv420p (Y plane then U, V at half resolution)")
    total = 0
    for rel, w, h in FILES:
        src = args.iwd2_root / rel
        if not src.is_file():
            print(f"!! missing {src}; skipping", file=sys.stderr)
            continue
        print(f"hashing {rel} ...", file=sys.stderr, flush=True)
        hashes = hash_frames(src, w, h)
        total += len(hashes)
        lines.append(f"[{rel}] {w} {h} {len(hashes)}")
        lines.extend(hashes)
        print(f"  {len(hashes)} frames", file=sys.stderr)

    out_path.write_text("\n".join(lines) + "\n")
    size = out_path.stat().st_size
    print(
        f"wrote {out_path} — {total} frames, {size} bytes",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
