[package]
name = "infinitier_bif_importer"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
description = ""
readme = "readme.md"
keywords = []

[dependencies]
infinitier_datasource = { workspace = true }
infinitier_key_importer = { workspace = true }

[dev-dependencies]
infinitier_test_utils = { workspace = true }
