[package]
name = "infinitier_two_da_importer"
version.workspace = true
edition.workspace = true

[dependencies]
infinitier_datasource = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }

[dev-dependencies]
infinitier_fs = { workspace = true }
infinitier_test_utils = { workspace = true }
