[package]
name = "infinitier_explorer_egui"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
infinitier_core = { workspace = true }

clap = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }

eframe = { workspace = true }
egui_extras = { workspace = true }
egui_ltreeview = { workspace = true }
