//! Container-parser corpus test against `assets/resources/BIK/`.
//!
//! Every `.bik` / `.mve` file in the asset folder ships with a
//! `<stem>.json` fixture (generated by the `gen_fixtures` example via
//! this crate's decoder). We parse the Bink header and assert the
//! dimensions, frame count, and audio track parameters match the
//! fixture — for both `BIKi` and `BIKb`.

mod common;

use std::fs::File;

use infinitier_bik_decoder::parse_header;

use crate::common::corpus;

#[test]
fn corpus_headers_match_fixtures() {
    let entries = corpus();
    for entry in &entries {
        let mut f = File::open(&entry.bik_path).unwrap_or_else(|e| {
            panic!("open {}: {}", entry.bik_path.display(), e)
        });
        let h = parse_header(&mut f)
            .unwrap_or_else(|e| panic!("parse {}: {}", entry.label(), e));

        let expected = &entry.fixture.video;
        assert_eq!(h.width, expected.width, "{}: width", entry.label());
        assert_eq!(h.height, expected.height, "{}: height", entry.label());
        assert_eq!(
            h.frames.len() as u32,
            expected.frame_count,
            "{}: frame_count",
            entry.label()
        );
        assert_eq!(
            &h.signature,
            expected.codec_tag.as_bytes(),
            "{}: codec_tag",
            entry.label()
        );

        // First frame is always a keyframe in the wild (and required for
        // motion compensation to ever bootstrap).
        assert!(
            h.frames[0].keyframe,
            "{}: first frame not keyframe",
            entry.label()
        );
        // Every frame's range must fit inside the file.
        for (i, fr) in h.frames.iter().enumerate() {
            assert!(
                fr.pos as u64 + fr.size as u64 <= h.file_size,
                "{}: frame {} extends past EOF",
                entry.label(),
                i
            );
            assert!(fr.size > 0, "{}: frame {} has zero size", entry.label(), i);
        }

        // Audio metadata round-trip: header should match the fixture's
        // claimed channels + sample-rate, and the fixture's presence/absence
        // of an `audio` block should mirror the file's track count. The
        // DCT-vs-RDFT discrimination is the audio decoder's concern, not
        // the container's, so we don't assert on it here.
        match (&entry.fixture.audio, h.audio_tracks.first()) {
            (Some(exp), Some(track)) => {
                assert_eq!(
                    track.sample_rate as u32,
                    exp.sample_rate,
                    "{}: audio sample_rate",
                    entry.label()
                );
                assert_eq!(
                    track.flags.channels() as u32,
                    exp.channels,
                    "{}: audio channels",
                    entry.label()
                );
            }
            (None, None) => { /* both agree this file has no audio */ }
            (Some(_), None) => panic!("{}: fixture has audio, header doesn't", entry.label()),
            (None, Some(_)) => panic!("{}: header has audio, fixture doesn't", entry.label()),
        }

        eprintln!(
            "ok  {:<24}  {} {}x{}, {} frames{}",
            entry.label(),
            expected.codec_tag,
            h.width,
            h.height,
            h.frames.len(),
            entry
                .fixture
                .audio
                .as_ref()
                .map(|a| format!(", audio {} Hz {}ch", a.sample_rate, a.channels))
                .unwrap_or_default(),
        );
    }
}

#[test]
fn rejects_non_bink_signature() {
    let buf: &[u8] = b"BOGUS\0\0\0";
    let mut cur = std::io::Cursor::new(buf);
    let err = parse_header(&mut cur).unwrap_err();
    assert!(matches!(
        err,
        infinitier_bik_decoder::BikError::BadSignature(_)
    ));
}
