//! Phase-6 corpus validation.
//!
//! Decodes every frame of every IWD2 cutscene file, hashes each decoded
//! frame's tightly-packed YUV420p output, and asserts the hash matches the
//! pre-recorded fixture (generated by `tests/fixtures/gen_iwd2_fixtures.py`
//! via FFmpeg).
//!
//! Skips silently when either the IWD2 install or the fixture file is
//! missing — the install isn't reproducible in CI, and the fixture can be
//! regenerated locally with the script above.

use std::fs::File;
use std::io::{Read, Seek, SeekFrom};
use std::path::PathBuf;

use infinitier_bik_decoder::{BikHeader, VideoDecoder, VideoFrame, parse_header};
use sha2::{Digest, Sha256};

fn iwd2_root() -> Option<PathBuf> {
    let p = std::env::var("IWD2_ROOT")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from("/home/ufo/Temp/Games/Icewind Dale 2"));
    if p.is_dir() { Some(p) } else { None }
}

/// One file's section in the fixtures text file.
#[derive(Debug)]
struct FixtureSection {
    rel_path: String,
    width: u32,
    height: u32,
    frame_hashes: Vec<[u8; 32]>,
}

/// Parse the `tests/fixtures/iwd2_frames.txt` file format.
///
/// ```text
/// # ... comments ...
/// [Data/BISlogo.mve] 640 320 185
/// abc123...   ; sha256 hex, one per line, exactly 64 chars
/// def456...
/// ...
/// [Data/Credits.mve] 640 320 1500
/// ...
/// ```
fn parse_fixtures(text: &str) -> Vec<FixtureSection> {
    let mut sections: Vec<FixtureSection> = Vec::new();
    let mut current: Option<FixtureSection> = None;
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some(rest) = line.strip_prefix('[') {
            // Section header: `[path] w h count`
            if let Some(end) = rest.find(']') {
                let rel_path = rest[..end].to_owned();
                let after = rest[end + 1..].trim();
                let mut parts = after.split_ascii_whitespace();
                let w: u32 = parts.next().unwrap().parse().unwrap();
                let h: u32 = parts.next().unwrap().parse().unwrap();
                let cnt: usize = parts.next().unwrap().parse().unwrap();
                if let Some(prev) = current.take() {
                    sections.push(prev);
                }
                current = Some(FixtureSection {
                    rel_path,
                    width: w,
                    height: h,
                    frame_hashes: Vec::with_capacity(cnt),
                });
            }
        } else {
            // 64-char sha256 hex.
            let cur = current
                .as_mut()
                .expect("hash line without preceding section header");
            assert_eq!(line.len(), 64, "expected 64-char sha256, got {:?}", line);
            let mut hash = [0u8; 32];
            for i in 0..32 {
                let byte = u8::from_str_radix(&line[i * 2..i * 2 + 2], 16)
                    .unwrap_or_else(|_| panic!("bad hex at byte {} of {:?}", i, line));
                hash[i] = byte;
            }
            cur.frame_hashes.push(hash);
        }
    }
    if let Some(last) = current {
        sections.push(last);
    }
    sections
}

/// Pack the decoder's stride-padded YUV planes into a tight `width × height`
/// + 2 chroma planes layout — the same layout `ffmpeg -f rawvideo -pix_fmt
/// yuv420p` produces and that the fixture script hashes.
fn pack_yuv420p(frame: &VideoFrame, w: u32, h: u32, out: &mut Vec<u8>) {
    let w = w as usize;
    let h = h as usize;
    let cw = w / 2;
    let ch = h / 2;
    out.clear();
    out.reserve(w * h + 2 * cw * ch);
    for row in 0..h {
        out.extend_from_slice(&frame.y.data[row * frame.y.stride..row * frame.y.stride + w]);
    }
    for row in 0..ch {
        out.extend_from_slice(&frame.u.data[row * frame.u.stride..row * frame.u.stride + cw]);
    }
    for row in 0..ch {
        out.extend_from_slice(&frame.v.data[row * frame.v.stride..row * frame.v.stride + cw]);
    }
}

fn read_packet(file: &mut File, pos: u32, size: u32, into: &mut Vec<u8>) {
    into.resize(size as usize, 0);
    file.seek(SeekFrom::Start(pos as u64)).unwrap();
    file.read_exact(into).unwrap();
}

/// `(frame_index, our_hash, expected_hash)` for a per-frame mismatch.
type Mismatch = (usize, [u8; 32], [u8; 32]);

fn run_one_file(
    path: &PathBuf,
    expected: &FixtureSection,
) -> Result<(usize, Vec<Mismatch>), String> {
    let mut f = File::open(path).map_err(|e| format!("open {}: {e}", path.display()))?;
    let header: BikHeader = parse_header(&mut f).map_err(|e| format!("parse: {e}"))?;
    if header.width != expected.width || header.height != expected.height {
        return Err(format!(
            "dimension mismatch: header {}x{}, fixture {}x{}",
            header.width, header.height, expected.width, expected.height
        ));
    }
    let n = expected.frame_hashes.len().min(header.frames.len());
    let mut decoder = VideoDecoder::new(&header).map_err(|e| format!("decoder: {e}"))?;

    let mut packet_buf: Vec<u8> = Vec::with_capacity(header.max_frame_size as usize);
    let mut yuv_buf: Vec<u8> = Vec::new();
    let mut mismatches: Vec<Mismatch> = Vec::new();

    for (i, fr) in header.frames.iter().take(n).enumerate() {
        read_packet(&mut f, fr.pos, fr.size, &mut packet_buf);
        let aud_len = u32::from_le_bytes([
            packet_buf[0],
            packet_buf[1],
            packet_buf[2],
            packet_buf[3],
        ]) as usize;
        let video_bytes = &packet_buf[4 + aud_len..];
        let frame = decoder
            .decode_frame(video_bytes)
            .map_err(|e| format!("frame {i}: {e}"))?;
        pack_yuv420p(frame, header.width, header.height, &mut yuv_buf);
        let mut hasher = Sha256::new();
        hasher.update(&yuv_buf);
        let got: [u8; 32] = hasher.finalize().into();
        let want = expected.frame_hashes[i];
        if got != want {
            mismatches.push((i, got, want));
            // Cap reports — once a frame mismatches, downstream frames almost
            // certainly do too because the prev-frame buffer is corrupt.
            if mismatches.len() >= 8 {
                break;
            }
        }
    }
    Ok((n, mismatches))
}

#[test]
fn iwd2_corpus_byte_exact_per_frame() {
    let Some(root) = iwd2_root() else {
        eprintln!("IWD2 install not found — skipping corpus test");
        return;
    };

    let fixtures_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("iwd2_frames.txt");
    if !fixtures_path.is_file() {
        eprintln!(
            "fixtures missing at {} — run gen_iwd2_fixtures.py to regenerate",
            fixtures_path.display()
        );
        return;
    }
    let fixtures_text = std::fs::read_to_string(&fixtures_path).unwrap();
    let sections = parse_fixtures(&fixtures_text);
    assert!(!sections.is_empty(), "no fixture sections parsed");

    let mut total_frames = 0usize;
    let mut total_mismatches = 0usize;
    let mut failed_files: Vec<String> = Vec::new();

    for sec in &sections {
        let path = root.join(&sec.rel_path);
        let label = &sec.rel_path;
        let start = std::time::Instant::now();
        match run_one_file(&path, sec) {
            Ok((n, mismatches)) => {
                let dt = start.elapsed();
                if mismatches.is_empty() {
                    eprintln!(
                        "✓  {:<24}  {} frames in {:.2}s",
                        label,
                        n,
                        dt.as_secs_f64()
                    );
                } else {
                    let first = &mismatches[0];
                    eprintln!(
                        "✗  {:<24}  {} mismatches (first @ frame {}: got {:02x}{:02x}.. want {:02x}{:02x}..)",
                        label,
                        mismatches.len(),
                        first.0,
                        first.1[0],
                        first.1[1],
                        first.2[0],
                        first.2[1],
                    );
                    failed_files.push(label.clone());
                    total_mismatches += mismatches.len();
                }
                total_frames += n;
            }
            Err(e) => {
                eprintln!("!! {}: {}", label, e);
                failed_files.push(label.clone());
            }
        }
    }

    eprintln!(
        "\nsummary: {} frames hashed, {} mismatches across {} failed files",
        total_frames,
        total_mismatches,
        failed_files.len()
    );

    assert!(
        failed_files.is_empty(),
        "{} files failed corpus validation: {:?}",
        failed_files.len(),
        failed_files,
    );
}
