[package]
name = "infinitier_ids_importer"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Reader for the IDS identifier reference format used in Infinity Engine games"
readme = "readme.md"
keywords = ["ids", "infinity-engine", "baldurs-gate"]

[dependencies]
infinitier_datasource = { workspace = true }
log = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
infinitier_test_utils = { workspace = true }
