[package]
name = "infinitier_core"
version.workspace = true
edition.workspace = true

[dependencies]
bitflags = { workspace = true }
image = { workspace = true }
infinitier_acm_decoder = { workspace = true }
infinitier_datasource = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
texture2ddecoder = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
