[package]
name = "infinitier_core"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
description = ""
readme = "readme.md"
keywords = []

[dependencies]
infinitier_bam_importer = { workspace = true }
infinitier_bif_importer = { workspace = true }
infinitier_bmp_importer = { workspace = true }
infinitier_ids_importer = { workspace = true }
infinitier_ini_importer = { workspace = true }
infinitier_key_importer = { workspace = true }
infinitier_pvr_importer = { workspace = true }
infinitier_two_da_importer = { workspace = true }
infinitier_wed_importer = { workspace = true }

[dev-dependencies]
infinitier_fs = { workspace = true }
infinitier_test_utils = { workspace = true }
