[package]
name = "infinitier_core"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Core game data model and resource loader for Infinity Engine games"
readme = "readme.md"
keywords = ["infinity-engine", "baldurs-gate", "game", "resources"]

[dependencies]
infinitier_common = { workspace = true }
infinitier_datasource = { workspace = true }
infinitier_fs = { workspace = true }

# Codecs
infinitier_acm_decoder = { workspace = true }
infinitier_bik_decoder = { workspace = true }
infinitier_mve_decoder = { workspace = true }
infinitier_wav_decoder = { workspace = true }
infinitier_wbm_decoder = { workspace = true }

# Resources
infinitier_bam_resource = { workspace = true }
infinitier_bcs_resource = { workspace = true }
infinitier_bif_resource = { workspace = true }
infinitier_bmp_resource = { workspace = true }
infinitier_ids_resource = { workspace = true }
infinitier_ini_resource = { workspace = true }
infinitier_key_resource = { workspace = true }
infinitier_mos_resource = { workspace = true }
infinitier_png_resource = { workspace = true }
infinitier_pvrz_resource = { workspace = true }
infinitier_tis_resource = { workspace = true }
infinitier_two_da_resource = { workspace = true }
infinitier_wed_resource = { workspace = true }

image = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
infinitier_test_utils = { workspace = true }
tempfile = { workspace = true }
