[package]
name = "infinitier_explorer"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[dependencies]
infinitier_core = { workspace = true }

bytesize = { workspace = true }
clap = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
image = { workspace = true }
smallvec = { workspace = true }
rodio = { workspace = true }

gpui = { workspace = true }
gpui-component = { workspace = true }
