[package]
name = "infinitier_explorer"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
infinitier_datasource = { workspace = true }
infinitier_fs = { workspace = true }
infinitier_key_importer = { workspace = true }

eframe = { workspace = true }
egui_extras = { workspace = true }
egui_ltreeview = { workspace = true }
