IF
    HPPercentLT(Myself,50)
    Global("STARTEDCHANGE","LOCALS",0)
THEN
    RESPONSE #100
        StartCutSceneMode()
        ClearAllActions()
        ReallyForceSpellRES("abzaway",Myself)  // No such index
        Wait(1)
        EndCutSceneMode()
        ReallyForceSpellRES("JWSP02",Myself)  // No such index
        SetGlobal("STARTEDCHANGE","LOCALS",1)
END

IF
    OR(2)
        Detect([PC])
        See(Player1)
    Global("SelfInit","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobal("SelfInit","LOCALS",1)
        StartDialogueNoSet(LastSeenBy(Myself))
END

