IF
    StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        ForceSpell(Myself,WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
END

IF
    Allegiance(Myself,ENEMY)
    !StateCheck(Myself,STATE_REALLY_DEAD)
    Global("prepspells","LOCALS",0)
THEN
    RESPONSE #100
        ApplySpell(Myself,WIZARD_SPELL_DEFLECTION)  // SPWI618.SPL (Spell Deflection)
        Wait(1)
        DisplayString(Myself,31247)  // Tattoo of Power—Spell Immunity
        ApplySpell(Myself,WIZARD_SPELL_IMMUNITY_INVOCATION)  // SPWI595.SPL (Immunity: Evocation)
        SetGlobal("prepspells","LOCALS",1)
END

IF
    Allegiance(Myself,ENEMY)
    Global("prepspells","LOCALS",1)
    CheckStatLT(Myself,1,STONESKINS)
    !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
    RESPONSE #100
        DisplayString(Myself,29736)  // Contingency—Stoneskin
        ApplySpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
        SetGlobal("prepspells","LOCALS",2)
END

IF
    Allegiance(Myself,ENEMY)
    See([GOODCUTOFF.0.0.0.0.SUMMONED])
    !Range(LastSeenBy(Myself),12)
    HaveSpell(WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
THEN
    RESPONSE #100
        DisplayString(Myself,31024)  // Magic Tattoo—Mirror Image
        ApplySpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
END

IF
    Allegiance(Myself,ENEMY)
    See([GOODCUTOFF.0.0.0.0.SUMMONED])
    Range(LastSeenBy(Myself),12)
    HaveSpell(WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
    HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
THEN
    RESPONSE #100
        DisplayString(Myself,31024)  // Magic Tattoo—Mirror Image
        ApplySpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
        Spell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
    Global("prepspells","LOCALS",2)
    HaveSpell(WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
    CheckStatLT(Myself,1,STONESKINS)
    !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

IF
    Allegiance(Myself,ENEMY)
    See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
    HaveSpell(WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
    HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
        Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
END

IF
    Allegiance(Myself,ENEMY)
    See(SecondNearestEnemyOf(Myself))
    !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
    Allegiance(Myself,ENEMY)
    See(ThirdNearestEnemyOf(Myself))
    !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END

IF
    See(SecondNearestEnemyOf(Myself))
    HaveSpell(WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
    HaveSpell(WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
THEN
    RESPONSE #100
        DisplayString(Myself,31024)  // Magic Tattoo—Mirror Image
        ApplySpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(SecondNearestEnemyOf(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
        Spell(SecondNearestEnemyOf(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
END

IF
    See(ThirdNearestEnemyOf(Myself))
    HaveSpell(WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
    !Range(LastSeenBy(Myself),12)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
    Allegiance(Myself,ENEMY)
    See(SixthNearestEnemyOf(Myself))
    HaveSpell(WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
    HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
    HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
    HaveSpell(WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
THEN
    RESPONSE #10
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(NearestEnemyOf(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
        Spell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
        Spell(NearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
    RESPONSE #10
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(SecondNearestEnemyOf(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
        Spell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
        Spell(SecondNearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
    RESPONSE #10
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(ThirdNearestEnemyOf(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
        Spell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
        Spell(ThirdNearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
    RESPONSE #10
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(FourthNearestEnemyOf(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
        Spell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
        Spell(FourthNearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
    RESPONSE #10
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(FifthNearestEnemyOf(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
        Spell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
        Spell(FifthNearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
    RESPONSE #10
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(SixthNearestEnemyOf(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
        Spell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
        Spell(SixthNearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
    Allegiance(Myself,ENEMY)
    See(FifthNearestEnemyOf(Myself))
    HaveSpell(WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
    HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
    HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
    HaveSpell(WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
THEN
    RESPONSE #10
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(NearestEnemyOf(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
        Spell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
        Spell(NearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
    RESPONSE #10
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(SecondNearestEnemyOf(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
        Spell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
        Spell(SecondNearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
    RESPONSE #10
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(ThirdNearestEnemyOf(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
        Spell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
        Spell(ThirdNearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
    RESPONSE #10
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(FourthNearestEnemyOf(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
        Spell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
        Spell(FourthNearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
    RESPONSE #10
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(FifthNearestEnemyOf(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
        Spell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
        Spell(FifthNearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
    Allegiance(Myself,ENEMY)
    See(FourthNearestEnemyOf(Myself))
    HaveSpell(WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
    HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
    HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
    HaveSpell(WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
THEN
    RESPONSE #10
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(NearestEnemyOf(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
        Spell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
        Spell(NearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
    RESPONSE #10
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(SecondNearestEnemyOf(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
        Spell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
        Spell(SecondNearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
    RESPONSE #10
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(ThirdNearestEnemyOf(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
        Spell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
        Spell(ThirdNearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
    RESPONSE #10
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(FourthNearestEnemyOf(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
        Spell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
        Spell(FourthNearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
    Allegiance(Myself,ENEMY)
    See(ThirdNearestEnemyOf(Myself))
    HaveSpell(WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
    HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
    HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
    HaveSpell(WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
THEN
    RESPONSE #10
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(NearestEnemyOf(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
        Spell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
        Spell(NearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
    RESPONSE #10
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(SecondNearestEnemyOf(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
        Spell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
        Spell(SecondNearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
    RESPONSE #10
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(ThirdNearestEnemyOf(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
        Spell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
        Spell(ThirdNearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
    Allegiance(Myself,ENEMY)
    See(SecondNearestEnemyOf(Myself))
    HaveSpell(WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
    HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
    HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
    HaveSpell(WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
THEN
    RESPONSE #10
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(NearestEnemyOf(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
        Spell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
        Spell(NearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
    RESPONSE #10
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(SecondNearestEnemyOf(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
        Spell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
        Spell(SecondNearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
    Allegiance(Myself,ENEMY)
    See(NearestEnemyOf(Myself))
    HaveSpell(WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
    HaveSpell(WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
    HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
    HaveSpell(WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
THEN
    RESPONSE #10
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(NearestEnemyOf(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
        Spell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)  // SPWI512.SPL (Protection From Electricity)
        Spell(NearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (Chain Lightning)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (Lightning Bolt)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),WIZARD_AGANNAZAR_SCORCHER)  // SPWI217.SPL (Agannazar's Scorcher)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(WIZARD_PHANTOM_BLADE)  // SPWI518.SPL (Phantom Blade)
    HaveSpell(WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
        Spell(Myself,WIZARD_PHANTOM_BLADE)  // SPWI518.SPL (Phantom Blade)
        AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        EquipMostDamagingMelee()
        AttackReevaluate(NearestEnemyOf(Myself),30)
END

