IF
    True()
THEN
    RESPONSE #100
        CutSceneId("GithAng")  // Yi'minn - Githyanki
        TimedMoveToPoint([2641.976],300)
        TimedMoveToPoint([3137.908],300)
        TimedMoveToPoint([3385.719],300)
        Face(SW)
        SetGlobal("Githzerai_Ambush_Spawn","GLOBAL",1)
        Wait(2)
        StartCutScene("0500cut2")
END

IF
    True()
THEN
    RESPONSE #100
        CutSceneId(Player1)
        Wait(1)
        MoveViewPoint([2641.976],VERY_FAST)
        TimedMoveToPoint([2641.976],300)
        MoveViewPoint([3137.908],VERY_FAST)
        TimedMoveToPoint([3137.908],300)
        MoveViewPoint([3385.719],VERY_FAST)
        TimedMoveToPoint([3319.754],300)
        Face(NE)
END

