//! Window lifecycle + callback wiring.
//!
//! Owns the `MainWindow` instance, hands it off to the `ui::*`
//! modules for the static "populate once at startup" pass, then
//! registers click callbacks. Also wires the `toggle-scheme`
//! callback that flips `slint::Palette::color-scheme` between Dark
//! and Light — the runtime-theming demo this spike exists to
//! showcase.

use slint::{ComponentHandle, Global};
use slint::language::ColorScheme;

use crate::state::AppState;
use crate::ui;
// `Palette` is generated by `slint::include_modules!()` in `main.rs`
// because main.slint re-exports the built-in `Palette` global. The
// generated struct exposes `set_color_scheme` / `get_color_scheme`
// via the `slint::Global` trait.
use crate::{ColorSchemeArg, MainWindow, Palette};

pub fn run(state: AppState, initial_scheme: ColorSchemeArg) {
    let state = state.into_rc();
    let window = MainWindow::new().expect("create MainWindow");

    // ── Initial palette ───────────────────────────────────────────
    // `Palette` is Slint's built-in global; the `Global::get(&window)`
    // pattern that slint-build emits returns a typed handle whose
    // `set_color_scheme` writes the in-out property. Every binding
    // that reads `Palette.*` (every panel paint we wrote in .slint)
    // re-evaluates — the whole UI repaints instantly.
    Palette::get(&window).set_color_scheme(initial_scheme.to_slint());

    // Static panes — set once at startup.
    ui::header::populate(&window, &state);
    ui::party::populate(&window, &state);
    ui::character::install_tab_strip(&window);

    // Initial selection / body draw.
    let initial_selection = if state.imported_gam.party_npcs.is_empty() {
        -1
    } else {
        0
    };
    window.set_selected_party(initial_selection);
    ui::character::refresh(&window, &state, initial_selection, 0);

    // ── Click callbacks ───────────────────────────────────────────
    {
        let weak = window.as_weak();
        let state = state.clone();
        window.on_party_clicked(move |idx| {
            if let Some(w) = weak.upgrade() {
                w.set_selected_party(idx);
                ui::character::refresh(&w, &state, idx, w.get_selected_tab());
            }
        });
    }
    {
        let weak = window.as_weak();
        let state = state.clone();
        window.on_tab_clicked(move |idx| {
            if let Some(w) = weak.upgrade() {
                w.set_selected_tab(idx);
                ui::character::refresh(&w, &state, w.get_selected_party(), idx);
            }
        });
    }
    {
        // The "Toggle theme" button in the header fires this. We
        // read the current scheme off `Palette` and flip between the
        // two explicit ones; `Unknown` (= follow OS) toggles to Dark.
        let weak = window.as_weak();
        window.on_toggle_scheme(move || {
            if let Some(w) = weak.upgrade() {
                toggle_color_scheme(&w);
            }
        });
    }

    window.run().expect("event loop");
}

/// Read the active color scheme on the window and flip it. Pulled
/// out into its own function so the demo intent is easy to spot —
/// this is the headline "Slint theming from Rust" pattern.
pub fn toggle_color_scheme(window: &MainWindow) {
    let palette = Palette::get(window);
    let next = match palette.get_color_scheme() {
        ColorScheme::Light => ColorScheme::Dark,
        // From Unknown (= follow OS) we explicitly pin Light so the
        // first click has a visible effect on every platform.
        ColorScheme::Dark | ColorScheme::Unknown | _ => ColorScheme::Light,
    };
    log::info!("Switching color scheme to {next:?}");
    palette.set_color_scheme(next);
}
